# https://goreleaser.com/customization/
project_name: skr
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
    main: ./cmd/skr/main.go

archives:
  - format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE*
      - README*

release:
  # Repo in which the release will be created.
  # Default is extracted from the origin remote URL.
  github:
    owner: elonzh
    name: skr

  # If set to true, will not auto-publish the release.
  # Default is false.
  draft: false

  # If set to true, will mark the release as not ready for production.
  # Default is false.
  prerelease: true

  # You can change the name of the GitHub release.
  # This is parsed with the Go template engine and the following variables
  # are available:
  # - ProjectName
  # - Tag
  # - Version (Git tag without `v` prefix)
  # Default is ``
  name_template: "{{.ProjectName}}-v{{.Version}}"

snapshot:
  name_template: SNAPSHOT-{{ .Timestamp }}-{{.Commit}}

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
dist: dist
sign:
  cmd: gpg
  args:
    - --output
    - $signature
    - --detach-sig
    - $artifact
  signature: ${artifact}.sig
  artifacts: none
